### PR TITLE
Trying to fix display of non-ASCII characters

### PR DESCRIPTION
**Pull request by aovanessian**
Please review/merge.

### CODE REVIEW

**Comment by KcrPL** [comment]
Looks good 👌

**Comment by spotlightishere** [comment]
@larsenv -- before we pull on server, can you confirm/deny UTF 8 would work here? I can't check myself but I know we had UTF-16 for a reason 😛 

Also good idea to change to utf-8 in the first place for encoding.

**Comment by larsenv** [comment]
@aovanessian, the Wii wants the AltName in base64-encoded UTF-16BE, since it uses that for a lot of stuff. Changing that would break the title of the message and give weird characters. I guess I can try to use utf-8 for the text. I'll test it out when I can. For now I'll revert it

**Comment by KcrPL** [comment]
Oops. sorry for merging it, next time you'll merge it.

**Pull request merged**
