### PR TITLE
Fixed Spanish

### PR DESCRIPTION
**Pull request by Tau5**
Fixed the spanish translation

### CODE REVIEW

**Comment by larsenv** [comment]
Could you tell me what was wrong with them to begin with?

**Comment by aovanessian** [comment]
@Tau5 seems to be a native speaker, so I'd trust his translation corrections :)

**Comment by Tau5** [comment]
@larsenv `abortar` is used when the process is running, `cancel` is used before the process,
also in this context `return` its more likely `devuelto` and not `volvió`

**Comment by larsenv** [comment]
OK, thanks.

**Pull request merged**
